execute @a[scores={Health=0}] ~ ~ ~ event entity @s h0
execute @a[scores={Health=1}] ~ ~ ~ event entity @s h1
execute @a[scores={Health=2}] ~ ~ ~ event entity @s h2
execute @a[scores={Health=3}] ~ ~ ~ event entity @s h3
execute @a[scores={Health=4}] ~ ~ ~ event entity @s h4
execute @a[scores={Health=5}] ~ ~ ~ event entity @s h5
execute @a[scores={Health=6}] ~ ~ ~ event entity @s h6
execute @a[scores={Health=7}] ~ ~ ~ event entity @s h7
execute @a[scores={Health=8}] ~ ~ ~ event entity @s h8
execute @a[scores={Health=9}] ~ ~ ~ event entity @s h9
execute @a[scores={Health=10}] ~ ~ ~ event entity @s h10
execute @a[scores={Health=11}] ~ ~ ~ event entity @s h11
execute @a[scores={Health=12}] ~ ~ ~ event entity @s h12
execute @a[scores={Health=13}] ~ ~ ~ event entity @s h13
execute @a[scores={Health=14}] ~ ~ ~ event entity @s h14
execute @a[scores={Health=15}] ~ ~ ~ event entity @s h15
execute @a[scores={Health=16}] ~ ~ ~ event entity @s h16
execute @a[scores={Health=17}] ~ ~ ~ event entity @s h17
execute @a[scores={Health=18}] ~ ~ ~ event entity @s h18
execute @a[scores={Health=19}] ~ ~ ~ event entity @s h19
execute @a[scores={Health=20}] ~ ~ ~ event entity @s h20
execute @a[scores={Health=21}] ~ ~ ~ event entity @s h21
execute @a[scores={Health=22}] ~ ~ ~ event entity @s h22
execute @a[scores={Health=23}] ~ ~ ~ event entity @s h23
execute @a[scores={Health=24}] ~ ~ ~ event entity @s h24
execute @a[scores={Health=25}] ~ ~ ~ event entity @s h25
execute @a[scores={Health=26}] ~ ~ ~ event entity @s h26
execute @a[scores={Health=27}] ~ ~ ~ event entity @s h27
execute @a[scores={Health=28}] ~ ~ ~ event entity @s h28
execute @a[scores={Health=29}] ~ ~ ~ event entity @s h29
execute @a[scores={Health=30}] ~ ~ ~ event entity @s h30
execute @a[scores={Health=31}] ~ ~ ~ event entity @s h31
execute @a[scores={Health=32}] ~ ~ ~ event entity @s h32
execute @a[scores={Health=33}] ~ ~ ~ event entity @s h33
execute @a[scores={Health=34}] ~ ~ ~ event entity @s h34
execute @a[scores={Health=35}] ~ ~ ~ event entity @s h35
execute @a[scores={Health=36}] ~ ~ ~ event entity @s h36
execute @a[scores={Health=37}] ~ ~ ~ event entity @s h37
execute @a[scores={Health=38}] ~ ~ ~ event entity @s h38
execute @a[scores={Health=39}] ~ ~ ~ event entity @s h39
execute @a[scores={Health=40}] ~ ~ ~ event entity @s h40